- name: index
  unique: true
  elements: [main_headline, text_block, single_picture, picture_gallery]
  autogenerate: [main_headline, text_block]

- name: standard
  elements: [main_headline, text_block, single_picture, picture_gallery]
  autogenerate: [main_headline, text_block]

- name: contact
  elements: [main_headline, text_block, contact_form]
  autogenerate: [main_headline, text_block, contact_form]
